name: Build unstable

on: [push]

concurrency: 
  group: unstable
#  cancel-in-progress: true


jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Create more disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc 
          sudo rm -rf "/usr/local/share/boost" 
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: ${{ secrets.DOCKERHUB_USERNAME }}/pdf-tei-editor
          registry: docker.io
          pushImage: ${{ github.event_name != 'pull_request' }}
          tags: latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
